version: "3"
# The service list for docker container group
services:
  # the service name, you could set it as custom name
  db_postgres:
    # just execute the image which image name and tag are corresponding the value
    image: postgres:10.3
    volumes:
      - db-data:/Users/core/Server/datas/data_store/postgres
      #- db-data:/Users/incubit-standard/Server/data/postgres

  webapp:
    # the build information for docker run command
    build:
      # the path for dockerfile
      context: .
      # the name of docker file
      dockerfile: Dockerfile
    
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    # the value is the tag information for the image when execute the [docker run] command with Dockerfile
    # It should be existed with build information
    image: rails-250-515:1.0
    ports:
      - 3000:3000
    volumes:
      - .:/StudyRailsOnRuby
    # express dependency between services, it means the services in [depends_on] will be started before the service
    depends_on:
      # the dependency services should be defined as a list
      - db_postgres

volumes:
  db-data: {}
